name: Only allow pull requests to master from staging
'on':
  pull_request:
    branches:
      - pipeline-test
jobs:
  print_pr_details:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR from ${{ github.head_ref }} to ${{ github.base_ref }}"
  fail_if_pr_not_from_staging:
    if: ne(${{ github.head_ref }}, pipeline-test-check-branch-name)
    runs-on: ubuntu-latest
    steps:
      - run: exit 1