name: Only allow pull requests to master from staging
'on':
  pull_request:
    branches:
      - pipeline-test
jobs:
  print_pr_details:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR from ${{ github.head_ref }} to ${{ github.base_ref }}"
  fail_if_pr_not_from_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Head ref not staging
        if: ${{ github.head_ref != 'pipeline-test-check-branch-name' }}
        run: echo "Head ref ${{ github.head_ref }} is not staging branch" && exit 1
      - name: Head ref is staging
        run: exit 0