name: Only allow pull requests to master from staging
'on':
  pull_request:
    branches:
      - pipeline-test
jobs:
  print_pr_details:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "PR from ${{ github.head_ref }} to ${{ github.base_ref }}"
  fail_if_pr_not_from_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: exit 1
      - condition: ne(${{ github.head_ref }}, staging)