name: Only allow pull requests to master from staging
'on':
  pull_request:
    branches:
      - pipeline-test
jobs:
  check_is_staging:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./inkstone-app
    steps:
      - uses: actions/checkout@v2
      - run: echo "Ref ${{ github.ref }}"
      - run: echo "Head ref ${{ github.head_ref }}"
      - run: echo "Base ref ${{ github.base_ref }}"